spring.application.name=ZMEN
# Database Configuration
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=abcd7;encrypt=true;trustServerCertificate=true;characterEncoding=UTF-8
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
# JPA Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.connection.characterEncoding=utf-8
spring.jpa.properties.hibernate.connection.CharSet=utf-8
spring.jpa.properties.hibernate.connection.useUnicode=true

# Server Configuration
server.port=8080
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

## HTTP encoding
#spring.http.encoding.charset=UTF-8
#spring.http.encoding.enabled=true
#spring.http.encoding.force=true

vietqr.api.url=https://api.vietqr.io/v2/
vietqr.client.id=9ac2d2e8-e22d-4c34-bc65-56e81b038425
vietqr.api.key=4fb61319-32fc-4a89-b31d-fc5da34c7f67

# Thông tin ngân hàng của bạn (để tạo mã QR)
vietqr.bank.id=970422
vietqr.account.number=0564746199999
vietqr.account.name=DANG LAM HUNG

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB